/* ═══════════════════════════════════════════════════════════
   PROOF OR BLUFF — real theorem, or plausible nonsense?
   Several pairs differ by one word. Those are the good ones.
   ═══════════════════════════════════════════════════════════ */

(function () {
  'use strict';

  /* t: true  = a genuine theorem
     t: false = a bluff, and w names the counterexample */

  const CLAIMS = [
    /* ── Theorems ── */
    { t: 1, s: 'Every finite integral domain is a field.',
           w: 'Multiplication by a nonzero element is injective, hence surjective.' },
    { t: 1, s: 'Every group of prime order is cyclic.',
           w: 'Any non-identity element generates the whole thing, by Lagrange.' },
    { t: 1, s: 'Every vector space has a basis.',
           w: 'Given the axiom of choice — Zorn’s lemma on independent sets.' },
    { t: 1, s: 'There are infinitely many primes.',
           w: 'Euclid, and about thirty proofs since.' },
    { t: 1, s: 'Every planar graph can be coloured with four colours.',
           w: 'The four colour theorem, 1976, with a great deal of computer assistance.' },
    { t: 1, s: 'Every real polynomial of odd degree has a real root.',
           w: 'It changes sign at the ends; the intermediate value theorem finishes it.' },
    { t: 1, s: 'The sum of the reciprocals of the primes diverges.',
           w: 'Euler. It diverges like log log n, which is slow even by these standards.' },
    { t: 1, s: 'Every subgroup of a cyclic group is cyclic.',
           w: 'Generated by the smallest positive exponent that appears.' },
    { t: 1, s: 'Every square matrix satisfies its own characteristic polynomial.',
           w: 'Cayley–Hamilton.' },
    { t: 1, s: 'Every real symmetric matrix is diagonalisable over ℝ.',
           w: 'The spectral theorem, and you even get an orthonormal eigenbasis.' },
    { t: 1, s: 'The continuous image of a compact set is compact.',
           w: 'Pull back an open cover and use compactness upstairs.' },
    { t: 1, s: 'Every bounded sequence in ℝⁿ has a convergent subsequence.',
           w: 'Bolzano–Weierstrass.' },
    { t: 1, s: 'Every finite field has prime power order.',
           w: 'It is a vector space over its prime subfield.' },
    { t: 1, s: 'Among any six people, three are mutual acquaintances or three are mutual strangers.',
           w: 'R(3,3) = 6. Five people is not enough.' },
    { t: 1, s: 'Every tree is bipartite.',
           w: 'Two-colour by parity of distance from a root. No cycles, no conflict.' },
    { t: 1, s: 'Every finite graph with minimum degree at least two contains a cycle.',
           w: 'Walk without repeating an edge; in a finite graph you must revisit a vertex.' },
    { t: 1, s: 'Every prime congruent to 1 mod 4 is a sum of two squares.',
           w: 'Fermat’s two-square theorem.' },
    { t: 1, s: 'Every ideal of ℤ is principal.',
           w: 'Take the smallest positive element and divide.' },
    { t: 1, s: 'Between any two distinct reals there is a rational.',
           w: 'Density of ℚ, via the Archimedean property.' },
    { t: 1, s: 'There are exactly five Platonic solids.',
           w: 'Euclid closes the Elements with it.' },
    { t: 1, s: 'π is transcendental.',
           w: 'Lindemann, 1882 — which is what finally killed squaring the circle.' },
    { t: 1, s: 'Every open subset of ℝ is a countable union of disjoint open intervals.',
           w: 'Take the connected components; each one contains a rational.' },
    { t: 1, s: 'Every group of order 15 is cyclic.',
           w: 'Sylow forces unique subgroups of order 3 and 5.' },
    { t: 1, s: 'A countable union of measure-zero sets has measure zero.',
           w: 'Cover the nth set to within ε/2ⁿ.' },
    { t: 1, s: 'Every connected graph has a spanning tree.',
           w: 'Keep deleting edges that lie on cycles.' },
    { t: 1, s: 'Every subgroup of index two is normal.',
           w: 'There are only two cosets, so the left and right ones coincide.' },
    { t: 1, s: 'The Cantor set is uncountable.',
           w: 'It is exactly the reals with a base-3 expansion avoiding the digit 1.' },
    { t: 1, s: 'Every continuous function on [0,1] is uniformly continuous.',
           w: 'Continuity on a compact set is automatically uniform.' },
    { t: 1, s: 'Every finite group is isomorphic to a subgroup of a symmetric group.',
           w: 'Cayley’s theorem — let the group act on itself.' },
    { t: 1, s: 'Every nonempty open subset of ℝ is uncountable.',
           w: 'It contains an interval, and every interval has the cardinality of ℝ.' },

    /* ── Bluffs ── */
    { t: 0, s: 'Every integral domain is a field.',
           w: 'ℤ is an integral domain and 2 has no inverse. Add "finite" and it becomes true.' },
    { t: 0, s: 'Every nonabelian group has a nontrivial centre.',
           w: 'The centre of S₃ is trivial. It is true for p-groups, which is the source of the confusion.' },
    { t: 0, s: 'Every infinite group has an element of infinite order.',
           w: 'The Prüfer group is infinite and every element has finite order.' },
    { t: 0, s: 'Every continuous function on ℝ is differentiable somewhere.',
           w: 'Weierstrass’s function is continuous everywhere and differentiable nowhere.' },
    { t: 0, s: 'Every subgroup of a group is normal.',
           w: '⟨(1 2)⟩ is not normal in S₃.' },
    { t: 0, s: 'Every group of order 12 is abelian.',
           w: 'A₄ has order 12 and is not abelian.' },
    { t: 0, s: 'Every field is algebraically closed.',
           w: 'x² + 1 has no root in ℝ, and ℚ is worse.' },
    { t: 0, s: 'The sum of two irrational numbers is irrational.',
           w: '√2 + (−√2) = 0.' },
    { t: 0, s: 'Every continuous function on ℝ is uniformly continuous.',
           w: 'x² is not. Compactness is what makes it work on [0,1].' },
    { t: 0, s: 'Every closed bounded subset of a metric space is compact.',
           w: 'Heine–Borel is a fact about ℝⁿ. The closed unit ball of ℓ² is not compact.' },
    { t: 0, s: 'Every planar graph can be coloured with three colours.',
           w: 'K₄ is planar and needs four.' },
    { t: 0, s: 'Every group of order p² is cyclic.',
           w: 'ℤ/p × ℤ/p is not. It is always abelian, though.' },
    { t: 0, s: 'Every complex square matrix is diagonalisable.',
           w: 'A single Jordan block is not. Over ℂ you only get triangularisable.' },
    { t: 0, s: 'Every injective linear map is surjective.',
           w: 'True in finite dimensions. The shift on ℓ² is injective and misses e₁.' },
    { t: 0, s: 'Every Cauchy sequence in a metric space converges.',
           w: 'That is the definition of complete, and ℚ is not.' },
    { t: 0, s: 'Every continuous bijection is a homeomorphism.',
           w: '[0,1) → S¹ by t ↦ e^(2πit) has no continuous inverse.' },
    { t: 0, s: 'Every real symmetric matrix has distinct eigenvalues.',
           w: 'The identity has one eigenvalue, repeated. Still diagonalisable, though.' },
    { t: 0, s: 'Every surjective group homomorphism is injective.',
           w: 'ℤ → ℤ/2 is onto with kernel 2ℤ.' },
    { t: 0, s: 'Every subring of a field is a field.',
           w: 'ℤ sits inside ℚ and is not a field.' },
    { t: 0, s: 'Every real polynomial of even degree has a real root.',
           w: 'x² + 1. Odd degree is the one that works.' },
    { t: 0, s: 'Every uncountable subset of ℝ contains an interval.',
           w: 'The Cantor set is uncountable and contains no interval at all.' },
    { t: 0, s: 'The rationals are a closed subset of ℝ.',
           w: 'Their closure is all of ℝ.' },
    { t: 0, s: 'Every nowhere dense set is finite.',
           w: 'The Cantor set is nowhere dense and uncountable.' },
    { t: 0, s: 'Every function with the intermediate value property is continuous.',
           w: 'The derivative of x² sin(1/x) has it and is discontinuous at 0.' },
    { t: 0, s: 'Every finite group of even order is abelian.',
           w: 'S₃ has order 6.' },
    { t: 0, s: 'Every ring with unity is commutative.',
           w: '2 × 2 matrices, for a start.' },
    { t: 0, s: 'Every bounded sequence converges.',
           w: '(−1)ⁿ is bounded and goes nowhere. Only a subsequence is promised.' },
    { t: 0, s: 'Every compact subset of a topological space is closed.',
           w: 'True in Hausdorff spaces. Without that, a single point need not even be closed.' },
    { t: 0, s: 'A group with a normal subgroup N is isomorphic to N × G/N.',
           w: 'ℤ/4 has a normal subgroup of order 2 but is not ℤ/2 × ℤ/2.' },
    { t: 0, s: 'Every abelian group is cyclic.',
           w: 'ℤ/2 × ℤ/2 is abelian and has no single generator.' }
  ];

  /* ─── State ──────────────────────────────────────────────── */

  const MAX_LIVES = 3;

  const S = {
    running: false,
    score: 0,
    best: Number(localStorage.getItem('proofbluff.best') || 0),
    streak: 0,
    lives: MAX_LIVES,
    bag: [],
    current: null,
    limit: 0,
    endsAt: 0,
    locked: true,
    lastTick: 0
  };

  const elClaim  = document.getElementById('claim');
  const elWhy    = document.getElementById('why');
  const elCard   = document.getElementById('card');
  const elMark   = document.getElementById('mark');
  const elScore  = document.getElementById('score');
  const elStreak = document.getElementById('streak');
  const elBest   = document.getElementById('best');
  const elLives  = document.getElementById('lives');
  const elTimer  = document.getElementById('timer-fill');
  const btnTrue  = document.getElementById('pick-true');
  const btnFalse = document.getElementById('pick-false');
  const overlay  = document.getElementById('overlay');

  function shuffle(a) {
    for (let i = a.length - 1; i > 0; i--) {
      const j = (Math.random() * (i + 1)) | 0;
      const t = a[i]; a[i] = a[j]; a[j] = t;
    }
    return a;
  }

  function mult() { return Math.min(5, 1 + Math.floor(S.streak / 3)); }
  function timeFor() { return Math.max(3.2, 5.6 - S.score / 4000); }

  /* ─── Rounds ─────────────────────────────────────────────── */

  function deal() {
    if (!S.bag.length) S.bag = shuffle(CLAIMS.slice());
    S.current = S.bag.pop();
    S.locked = false;

    elCard.className = 'claim-card';
    elMark.textContent = '';
    elWhy.textContent = '';
    elWhy.className = 'why';
    elClaim.textContent = S.current.s;
    btnTrue.disabled = false;
    btnFalse.disabled = false;

    S.limit = timeFor();
    S.endsAt = Date.now() + S.limit * 1000;
    S.lastTick = 0;
    SFX.deal();
    render();
  }

  function answer(saidTheorem) {
    if (!S.running || S.locked) return;
    S.locked = true;
    btnTrue.disabled = true;
    btnFalse.disabled = true;

    const correct = saidTheorem === Boolean(S.current.t);
    const left = Math.max(0, (S.endsAt - Date.now()) / 1000);

    if (correct) {
      SFX.right();
      const pts = (100 + Math.round(left * 15)) * mult();
      S.score += pts;
      S.streak++;
      elCard.classList.add('is-right');
      elMark.textContent = '✓';
      elWhy.className = 'why is-good';
      elWhy.textContent = (S.current.t ? 'Theorem. ' : 'Bluff. ') + S.current.w + '   +' + pts;
    } else {
      SFX.wrong();
      S.streak = 0;
      S.lives--;
      elCard.classList.add('is-wrong');
      elMark.textContent = '✗';
      elWhy.className = 'why is-bad';
      elWhy.textContent = (S.current.t ? 'It is a theorem. ' : 'It is a bluff. ') + S.current.w;
    }

    render();
    if (S.lives <= 0) { setTimeout(gameOver, 1500); return; }
    setTimeout(deal, correct ? 1500 : 2600);
  }

  function timeUp() {
    if (S.locked) return;
    S.locked = true;
    btnTrue.disabled = true;
    btnFalse.disabled = true;
    SFX.wrong();
    S.streak = 0;
    S.lives--;
    elCard.classList.add('is-wrong');
    elMark.textContent = '⏱';
    elWhy.className = 'why is-bad';
    elWhy.textContent = 'Too slow. ' + (S.current.t ? 'It was a theorem. ' : 'It was a bluff. ') + S.current.w;
    render();
    if (S.lives <= 0) { setTimeout(gameOver, 1500); return; }
    setTimeout(deal, 2600);
  }

  /* ─── Loop ───────────────────────────────────────────────── */

  function tick() {
    if (!S.running || S.locked) return;
    const left = S.endsAt - Date.now();
    elTimer.style.width = Math.max(0, Math.min(100, (left / (S.limit * 1000)) * 100)) + '%';
    elTimer.classList.toggle('is-low', left < 1600);
    const whole = Math.ceil(left / 1000);
    if (left < 3200 && whole !== S.lastTick) { S.lastTick = whole; SFX.tick(); }
    if (left <= 0) timeUp();
  }

  function render() {
    elScore.textContent = S.score.toLocaleString();
    elStreak.textContent = '×' + mult();
    elStreak.classList.toggle('is-hot', mult() >= 3);
    elBest.textContent = S.best.toLocaleString();
    [...elLives.querySelectorAll('i')].forEach((m, i) => {
      m.classList.toggle('is-gone', i >= S.lives);
    });
  }

  /* ─── Screens ────────────────────────────────────────────── */

  function show(html) { overlay.innerHTML = html; overlay.classList.add('is-open'); }

  function startScreen() {
    show(
      '<div class="card">' +
      '<div class="card-kicker">Real result, or plausible nonsense?</div>' +
      '<h1 class="card-title">Proof <span>or Bluff</span></h1>' +
      '<p class="card-body">A statement goes up. Decide whether it is <strong>a theorem</strong> ' +
      'or <strong>a bluff</strong> before the clock runs out.</p>' +
      '<ul class="card-rules">' +
        '<li>Several statements differ from a real theorem by one word. Those are the good ones.</li>' +
        '<li>Answer quickly for more points; three correct in a row starts a multiplier.</li>' +
        '<li>Three mistakes and you are done. Being too slow counts as a mistake.</li>' +
        '<li>Keys: <b>T</b> or <b>←</b> for theorem, <b>B</b> or <b>→</b> for bluff.</li>' +
      '</ul>' +
      '<button class="btn" id="start-btn">Deal the first one</button>' +
      '<a class="card-back" href="../index.html">← Back to the Common Room</a>' +
      '</div>'
    );
    document.getElementById('start-btn').addEventListener('click', start);
  }

  function gameOver() {
    S.running = false;
    SFX.over();
    const isBest = S.score > S.best;
    if (isBest) { S.best = S.score; localStorage.setItem('proofbluff.best', String(S.best)); }
    show(
      '<div class="card">' +
      '<div class="card-kicker">Out of credibility</div>' +
      '<h1 class="card-title">The referee<br><span>is unconvinced</span></h1>' +
      '<div class="result">' +
        '<div><b>' + S.score.toLocaleString() + '</b><span>Score</span></div>' +
        '<div><b>' + S.best.toLocaleString() + '</b><span>Best</span></div>' +
      '</div>' +
      (isBest ? '<p class="card-body card-best">A new best.</p>' : '') +
      '<button class="btn" id="again-btn">Again</button>' +
      '<a class="card-back" href="../index.html">← Back to the Common Room</a>' +
      '</div>'
    );
    document.getElementById('again-btn').addEventListener('click', start);
    render();
  }

  function start() {
    SFX.unlock();
    overlay.classList.remove('is-open');
    S.score = 0; S.streak = 0; S.lives = MAX_LIVES;
    S.bag = shuffle(CLAIMS.slice());
    S.running = true;
    render();
    deal();
  }

  /* ─── Wiring ─────────────────────────────────────────────── */

  btnTrue.addEventListener('click', () => answer(true));
  btnFalse.addEventListener('click', () => answer(false));

  document.addEventListener('keydown', (e) => {
    if (!S.running) return;
    const k = e.key.toLowerCase();
    if (k === 't' || k === 'arrowleft')  { e.preventDefault(); answer(true); }
    if (k === 'b' || k === 'arrowright') { e.preventDefault(); answer(false); }
  });

  let hiddenAt = 0;
  document.addEventListener('visibilitychange', () => {
    if (!S.running) return;
    if (document.hidden) hiddenAt = Date.now();
    else if (hiddenAt) { S.endsAt += Date.now() - hiddenAt; hiddenAt = 0; }
  });

  render();
  startScreen();
  setInterval(tick, 80);

})();
